### ISSUE TITLE
Update Deprecated Emoji Extension in mkdocs.yml

### ISSUE THREAD

**Issue by Eeshu-Yadav** [intelowlproject/docs#32]
**Description:**
The documentation currently uses a deprecated `materialx.emoji.twemoji` extension in `mkdocs.yml`. MkDocs Material version 9.4 has moved emoji support into the core `mkdocs-material` package, and `materialx` is no longer supported.

**Proposed Fix:**
Update `mkdocs.yml` to replace:

```yaml
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
```

with:
```yaml
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
```
**Expected Outcome:**
No deprecation warnings when running `mkdocs serve`.
Documentation remains fully functional.
